# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ModuleNotFoundError: No module named 'nbformat'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

2.2.6


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(null_vector.nbytes)


80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
y = np.flip(x)
y

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
matrix = np.array([[0,1,2],[3,4,5],[6,7,8]])
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
x = np.array([1,2,0,0,4,0])
indices = np.nonzero(x)
indices

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
identity_matrix = np.identity(3,dtype=int)
identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
m = np.random.rand(3,3,3)
m

array([[[0.50302252, 0.64539031, 0.2111523 ],
        [0.22143173, 0.5876138 , 0.2273136 ],
        [0.90069878, 0.76254885, 0.79088467]],

       [[0.98131345, 0.76308061, 0.75203765],
        [0.1521996 , 0.78365771, 0.89863619],
        [0.02963754, 0.70875003, 0.25354569]],

       [[0.01473326, 0.90091933, 0.21178537],
        [0.76021655, 0.50982161, 0.10430142],
        [0.51508366, 0.7133008 , 0.95540349]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [3]:

m = np.random.random((10,10))
print(m)
print(m.max())
print(m.min())

[[0.04842042 0.78885197 0.16670359 0.52512596 0.91493131 0.55789751
  0.28515719 0.63058242 0.90946537 0.33321385]
 [0.67113533 0.11791836 0.1428078  0.85665872 0.91748831 0.43534057
  0.87316246 0.25755715 0.75991455 0.14414324]
 [0.75485976 0.14027559 0.93973005 0.93874791 0.99849123 0.3840779
  0.23076559 0.93187035 0.68536471 0.29827983]
 [0.65233904 0.45787187 0.99314446 0.91219051 0.39528364 0.80916402
  0.49254223 0.75741293 0.36333601 0.38581725]
 [0.55661358 0.90000746 0.75235712 0.71677879 0.3690786  0.06753132
  0.64522912 0.08128941 0.31893677 0.47246926]
 [0.03600039 0.94463582 0.5692486  0.26682926 0.18916123 0.60228532
  0.1746222  0.01761221 0.91098931 0.24210997]
 [0.94649667 0.53455838 0.0988475  0.3372734  0.67931551 0.75425962
  0.1994476  0.02664631 0.19350222 0.81616925]
 [0.67682367 0.2244795  0.1293325  0.15536201 0.86897272 0.70077388
  0.65052352 0.5585649  0.83639679 0.53334397]
 [0.27350478 0.402058   0.54292055 0.4700112  0.57127959 0.61571893
  0.0113825  

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [29]:
random_vector = np.random.random((30))
print(random_vector)

print("Mean value of the vector of size 30 is :",np.mean(random_vector))

[0.95589491 0.86903037 0.54181825 0.22454911 0.89935719 0.17454434
 0.80232779 0.61627029 0.43573971 0.95812812 0.94876644 0.99986277
 0.6469941  0.3912611  0.9727053  0.52283504 0.88259052 0.02300176
 0.29669421 0.1489713  0.52671347 0.19815033 0.08022057 0.44601559
 0.18947883 0.66056005 0.96156414 0.72169915 0.41433546 0.63820101]
Mean value of the vector of size 30 is : 0.57160937348524


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [12]:
#in general 
#x = np.array(([1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]))
#print(x)

import numpy as np

def create_border(rows, coloumns):
    if rows < 2 or coloumns < 2:
        return np.ones((rows,coloumns))
    
    arr = np.ones((rows,coloumns),dtype = int)

    arr[1:-1,1:-1]=0

    return arr

rows = 2
coloumns = 1
result = create_border(rows,coloumns)
result

array([[1.],
       [1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [4]:
original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(original_array)

padded_array = np.pad(original_array,pad_width = 1, mode ='constant',constant_values=0)
print(padded_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [16]:
#### 17. What is the result of the following expression? (★☆☆)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
# due to floating point precision errors; use builtin in numpy function - isclose()
print(np.isclose(0.3,3*0.1))


nan
False
False
nan
True
False
True


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
matrix = np.zeros((5,5),dtype = int)

matrix[1,0] = 1
matrix[2,1] = 2
matrix[3,2] = 3
matrix[4,3] = 4

print(matrix)

#Best One liner
matrix = np.diag([1,2,3,4],k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
matrix = np.zeros((8,8),dtype=int)

matrix[::2,1::2] = 1
matrix[1::2,::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [36]:
shape = (6,7,8)
index = 99

result = np.unravel_index(index,shape)
print(result)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [38]:
base = np.array([[0,1],
                 [1,0]])
checkerboard = np.tile(base,(4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [66]:
#Normalization of a Matrix
matrix = np.random.randint(low = 5, high = 100, size=(5,5))
print(matrix)

#1. MIN - MAX Normalization : scale b/w 0 and 1 
    #formula: (matrix - matrix.min())/(matrix.max()-matrix.min())
min_max_normalization = (matrix - matrix.min())/(matrix.max()-matrix.min())
print("1.MIN - MAX Normalization: ")
print(min_max_normalization)

#2. Standardization (Z- score Normalization): 
    #formula = (matrix - np.mean(matrix))/np.std(matrix)

standardization = (matrix - np.mean(matrix))/np.std(matrix)
print("2. Standardization Normalization")
print(standardization)

print(standardization.mean())#should be approx 0 
print(standardization.std())# shoudl be approx 1 



[[68 99 20 37 81]
 [30  9 71 24 92]
 [72 33 52 89  7]
 [45 47 26 48 26]
 [82 36 80  8 36]]
1.MIN - MAX Normalization: 
[[0.66304348 1.         0.14130435 0.32608696 0.80434783]
 [0.25       0.02173913 0.69565217 0.18478261 0.92391304]
 [0.70652174 0.2826087  0.48913043 0.89130435 0.        ]
 [0.41304348 0.43478261 0.20652174 0.44565217 0.20652174]
 [0.81521739 0.31521739 0.79347826 0.01086957 0.31521739]]
2. Standardization Normalization
[[ 0.69765304  1.81939808 -1.0392425  -0.42409199  1.16806225]
 [-0.67738926 -1.43728106  0.80620901 -0.8945012   1.56610081]
 [ 0.84239434 -0.56883329  0.11868786  1.45754484 -1.50965171]
 [-0.1346094  -0.06223876 -0.82213056 -0.02605343 -0.82213056]
 [ 1.20424758 -0.46027732  1.13187693 -1.47346638 -0.46027732]]
5.551115123125783e-17
1.0


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [2]:
import numpy as np

rgba_dt = np.dtype([('r', 'u1'),
                    ('g', 'u1'),
                    ('b', 'u1'),
                    ('a', 'u1')])

# create an array of 3 colors
colors = np.zeros(3, dtype=rgba_dt)

# assign a color: red, green, blue, alpha
colors[0] = (255, 0, 0, 255)     # opaque red
colors[1] = (0, 255, 0, 128)     # semi-transparent green
colors[2] = (0, 0, 255, 64)      # translucent blue

print(colors)
# Access channels:
print(colors['r'])   # array([255,   0,   0], dtype=uint8)
print(colors[1]['g']) # 255


[(255,   0,   0, 255) (  0, 255,   0, 128) (  0,   0, 255,  64)]
[255   0   0]
255


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [6]:
A = np.random.randint(1,10,size=(5,3))
B = np.random.randint(1,10,size= (3,2))

print(A)
print()
print(B)

C= np.dot(A,B)
print("Real matrix product : ")
print(C)

[[6 7 5]
 [7 5 8]
 [3 5 2]
 [9 2 7]
 [6 2 8]]

[[7 2]
 [5 2]
 [9 7]]
Real matrix product : 
[[122  61]
 [146  80]
 [ 64  30]
 [136  71]
 [124  72]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [9]:
arr = np.arange(10)

mask = (arr>3) & (arr<8)

print("masked : ",mask)

arr[mask] *= -1

print(arr)

masked :  [False False False False  True  True  True  True False False]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [3]:
print(sum(range(5),-1))

9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [10]:
Z=2
Z**Z



4

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [14]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\GAGAN\AppData\Local\Temp\ipykernel_24364\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [16]:
arr = np.array([1.2,1.7,-1.3,-2.6,5.3,-6.7])
print(arr)

rounded_away_from_zero = np.copysign(np.ceil(np.abs(arr)),arr)
print(rounded_away_from_zero)

[ 1.2  1.7 -1.3 -2.6  5.3 -6.7]
[ 2.  2. -2. -3.  6. -7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [12]:
#Finding common elements (intersection) between arrays is one of those things you’ll do everywhere — in data preprocessing, filtering, joins, and even set operations.

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
#The cleanest built-in way is:
common = np.intersect1d(a,b)
print(common)

#np.intersect1d() finds elements present in both arrays.It also:Returns sorted unique results by default.Works on any 1D arrays (integer, float, string, etc.).

#By default,intersect1d() sorts the result. if you want to preserve the order of a and b use - .isin()

common = a[np.isin(a,b)]
print(common)

#For higher dimensions :
A = np.array([[7, 8, 9],
              [4, 5, 6]])

B = np.array([[4, 5, 6],
              [7, 8, 9]])

common = np.intersect1d(A,B)
print(common)
#np.intersect1d automatically flattens them before comparing.

"""
Bonous - Find unique, intersection, union, and set difference
| Operation      | Function               | Example             | Output              |
| -------------- | ---------------------- | ------------------- | ------------------- |
| Intersection   | `np.intersect1d(a, b)` | common elements     | `[4 5]`             |
| Union          | `np.union1d(a, b)`     | all unique elements | `[1 2 3 4 5 6 7 8]` |
| Difference     | `np.setdiff1d(a, b)`   | in `a` not in `b`   | `[1 2 3]`           |
| Symmetric diff | `np.setxor1d(a, b)`    | in one but not both | `[1 2 3 6 7 8]`     |
"""


[4 5]
[4 5]
[4 5 6 7 8 9]


'\nBonous - Find unique, intersection, union, and set difference\n| Operation      | Function               | Example             | Output              |\n| -------------- | ---------------------- | ------------------- | ------------------- |\n| Intersection   | `np.intersect1d(a, b)` | common elements     | `[4 5]`             |\n| Union          | `np.union1d(a, b)`     | all unique elements | `[1 2 3 4 5 6 7 8]` |\n| Difference     | `np.setdiff1d(a, b)`   | in `a` not in `b`   | `[1 2 3]`           |\n| Symmetric diff | `np.setxor1d(a, b)`    | in one but not both | `[1 2 3 6 7 8]`     |\n'

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [17]:
#sometimes during experiments (especially with EDA, vectorized math, division by zero, NaNs, etc.) NumPy throws RuntimeWarnings that you may want to temporarily suppress.

np.seterr(all = 'ignore')

#To restore default behaviour :
np.seterr(all = 'warn')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

# FALSE : Because the two functions behave very differently when handling negative numbers.

# np.sqrt() - is a real valued function. If you give a number that has no real square root it returns Nan
#np.emath.sqrt() belongs to NumPy’s "extended math" module for complex-aware versions of math functions.
#It automatically promotes values to complex numbers when needed. Output : 1j



C:\Users\GAGAN\AppData\Local\Temp\ipykernel_18408\2679886853.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [24]:
#NumPy has a very clean way to handle date arithmetic using np.datetime64 and np.timedelta64.
today = np.datetime64('today')
yesterday =today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D') # np.timedelta64(1, 'D') : Represents 1 Day

print(today, yesterday, tomorrow)

# Alternative : Use pythons datetime module 
from datetime import date, timedelta

today = date.today()
yesterday = today - timedelta(days = 1)
tomorrow = today + timedelta(days = 1)

print(today, yesterday, tomorrow)


2025-12-04 2025-12-03 2025-12-05
2025-12-04 2025-12-03 2025-12-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [25]:
dates = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


Explanation
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

'2016-07' → interpreted as 2016-07-01

'2016-08' → interpreted as the start of next month
→ so the range stops right before it

dtype='datetime64[D]' → generate daily dates

NumPy automatically generates all 31 days between the start of July and start of August.

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [26]:
A = np.array([2., 4., 6.])
B = np.array([1., 1., 1.])

B += A        # B = A + B
A /= -2       # A = -A/2
B *= A        # B = (A+B) * (-A/2)

print(B)

[ -3. -10. -21.]


Goal: Compute this without making any new arrays:
✅ Easiest in-place solution (modify B to hold the final answer)
B += A     # Step 1: B becomes (A + B)
A /= -2    # Step 2: A becomes (-A/2)
B *= A     # Step 3: B becomes (A+B)*(-A/2)

🧠 Why it works (super simple)

B += A
→ B now holds (A + B)

A /= -2
→ A now holds (−A/2)

B *= A
→ final answer stored in B
→ (A + B) * (−A/2)

🔥 Final result is in B

No extra arrays are created. Everything is done in place.

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [3]:
import numpy as np

arr = np.random.uniform(0,10,5)
print(arr)

method_1 = np.floor(arr)
print(method_1)

method_2 = arr.astype(int)
print(method_2)

method_3 = np.trunc(arr)
print(method_3)

frac, method_4 = np.modf(arr)
print(method_4)
print(frac)

[2.78936229 9.92426295 5.81240393 8.29274185 1.80649187]
[2. 9. 5. 8. 1.]
[2 9 5 8 1]
[2. 9. 5. 8. 1.]
[2. 9. 5. 8. 1.]
[0.78936229 0.92426295 0.81240393 0.29274185 0.80649187]


🧩 Method 1 — Using np.floor()

Rounds down to the nearest integer → works perfectly for positive numbers.

Method 2 — Using .astype(int) (type casting)

This simply truncates the decimal part. Works correctly for positive numbers.
(Be careful: negative numbers would round toward zero.)

🧩 Method 3 — Using np.trunc()
Truncates fractional part (toward zero).
Equivalent to .astype(int) for positive values.

🧩 Method 4 — Using np.modf()

Splits array into (fractional_part, integer_part) 
np.modf(arr) returns:
fractional part
integer part


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [5]:
matrix = np.indices((5,5))[1]
print(matrix)

matrix = np.tile(np.arange(5),(5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)